import React from "react"
import styled from "styled-components"
import { themeGet } from "@styled-system/theme-get"

import Layout from "../components/Layout"
import { Heading, Paragraph } from "../components/styles"

const Container = styled.section`
  width: calc(100% - ${themeGet("space.5")} * 2);
  max-width: 80rem;
  margin: auto;
  padding-top: 16rem;
  padding-bottom: 8rem;

  ${themeGet("media.phone")} {
    width: calc(100% - ${themeGet("space.2")} * 2);
    max-width: calc(${themeGet("pageMaxWidth")} - ${themeGet("space.2")} * 2);
    overflow: hidden;
  }

  a {
    text-decoration: underline;
    font-weight: 500;
  }
`

const PrivacyPage = () => (
  <Layout>
    <Container>
      <Heading as="h1" fontSize={4} fontWeight="semiBold">
        Privacy Policy
      </Heading>
      <Paragraph>
        Your privacy is important to us. It is Convo's policy to respect your
        privacy regarding any information we may collect from you across our
        website, <a href="https://hiconvo.com">https://hiconvo.com</a>,{" "}
        <a href="https://app.hiconvo.com">https://app.hiconvo.com</a>, and other
        sites we own and operate.
      </Paragraph>
      <Paragraph>
        We only ask for personal information when we truly need it to provide a
        service to you. We collect it by fair and lawful means, with your
        knowledge and consent. We also let you know why we’re collecting it and
        how it will be used.
      </Paragraph>
      <Paragraph>
        We only retain collected information for as long as necessary to provide
        you with your requested service. What data we store, we’ll protect
        within commercially acceptable means to prevent loss and theft, as well
        as unauthorised access, disclosure, copying, use or modification.
      </Paragraph>
      <Paragraph>
        We don’t share any personally identifying information publicly or with
        third-parties, except when required to by law.
      </Paragraph>
      <Paragraph>
        Our website may link to external sites that are not operated by us.
        Please be aware that we have no control over the content and practices
        of these sites, and cannot accept responsibility or liability for their
        respective privacy policies.
      </Paragraph>
      <Paragraph>
        You are free to refuse our request for your personal information, with
        the understanding that we may be unable to provide you with some of your
        desired services.
      </Paragraph>
      <Paragraph>
        Your continued use of our website will be regarded as acceptance of our
        practices around privacy and personal information. If you have any
        questions about how we handle user data and personal information, feel
        free to contact us.
      </Paragraph>
      <Paragraph>This policy is effective as of 28 October 2019.</Paragraph>
      <Paragraph>
        Generated by{" "}
        <a
          title="Privacy Policy Template Generator"
          href="https://getterms.io/"
        >
          GetTerms.io
        </a>
      </Paragraph>
      <Paragraph>
        Convo is owned and operated by Alexander Richey in Seattle, Washington.
      </Paragraph>
    </Container>
  </Layout>
)

export default PrivacyPage
